异常处理就是当异常发生时，对异常处理的方式


# 1 异常处理方法

try-catch-finally: 程序员在代码块中捕获发生的异常，自行处理
![](https://img-blog.csdnimg.cn/f12db9aeb99b4a87a5357f0f523b5e14.png?x-oss-process=image/watermark,type_d3F5LXplbmhlaQ,shadow_50,text_Q1NETiBA5Y-v5Y-v54ix54ix55qE5bCP56eD5aS0,size_12,color_FFFFFF,t_70,g_se,x_16)

throws: 将发生的异常抛出，交给调用者来处理，最顶级的处理者是JVM
![](https://img-blog.csdnimg.cn/2e390b9980a54031ab522c26f3f3922e.png?x-oss-process=image/watermark,type_d3F5LXplbmhlaQ,shadow_50,text_Q1NETiBA5Y-v5Y-v54ix54ix55qE5bCP56eD5aS0,size_14,color_FFFFFF,t_70,g_se,x_16)


# 2 默认的异常处理方式
如通过你不加 try-catth 没有手动加入 throws.  
那么系统会隐形的帮你加入 throws 

比如
```java
public static void main (String[] args){

}

等效于 
public static void main (String[] args) throws Exception{

}

```


# 3 try-catch方式处理异常

try 块用于包括可能出错的代码
Catch块 用于处理try块中发生的异常. 
程序中可以有多个 try..catch 块       
fianlly 有没有无所谓

 1)如果异常发生了，则异常发生后面的代码不会执行，直接进入到catch块. 如果有finally, 最后还需要执行finally 里面的语句 
 2)如果异常没有发生，则顺序执行try的代码块，不会进入到catch. 如果有finally, 最后还需要执行finally 里面的语句 
 3)如果希望不管是否发生异常，都执行某段代码(比如关闭连接，释放资源等)则使用如下代码- finally
 4)如果存在 finally的话, 在执行完 finally 块中内的命令后, 才会 退出 整个 try-catch-finally块 , 返回到 上一级的函数


简单案例

```java
int num1 = 10; 
int num2 = 0; 
try {
int res = num1 / num2; 
} catch (Exception e) { 
System.out.println(e.getMessage()); }
```


## 3.1 使用细节

细节1.
 1)如果异常发生了，则异常发生后面的代码不会执行，直接进入到catch块. 如果有finally, 最后还需要执行finally 里面的语句 
 2)如果异常没有发生，则顺序执行try的代码块，不会进入到catch. 如果有finally, 最后还需要执行finally 里面的语句 
 3)如果希望不管是否发生异常，都执行某段代码(比如关闭连接，释放资源等)则使用如下代码- finally
 4)如果存在 finally的话, 在执行完 finally 块中内的命令后, 才会 退出 整个 try-catch-finally块 , 返回到 上一级的函数

```java
//ctrl + atl + t快捷键try-catch

//1. 如果异常发生了，则异常发生后面的代码不会执行，直接进入到catch块
//2. 如果异常没有发生，则顺序执行try的代码块，不会进入到catch
//3. 如果希望不管是否发生异常，都执行某段代码(比如关闭连接，释放资源等)则使用如下代码- finally
try {
	String str = "韩顺平";
	int a = Integer.parseInt(str);
	System.out.println("数字：" + a);
} catch (NumberFormatException e) {
	System.out.println("异常信息=" + e.getMessage());
} finally {
	System.out.println("finally代码块被执行...");
}

System.out.println("程序继续...");
```



细节2.
1）如果try代码块有可能有多个异常
2）可以使用多个catch 分别捕获不同的异常，相应处理
3）catch 分别捕获不同的异常的顺序, 要求子类异常写在前面，父类异常写在后面
```java
class Person {
	private String name = "jack";
 
	public String getName() {
		return name;
	}
}
 
//1.如果try代码块有可能有多个异常
//2.可以使用多个catch 分别捕获不同的异常，相应处理
//3.要求子类异常写在前面，父类异常写在后面
try {
	Person person = new Person();
	//person = null;
	System.out.println(person.getName());//NullPointerException
	int n1 = 10;
	int n2 = 0;
	int res = n1 / n2;//ArithmeticException
} catch (NullPointerException e) {
	System.out.println("空指针异常=" + e.getMessage());
} catch (ArithmeticException e) {
	System.out.println("算术异常=" + e.getMessage());
} catch (Exception e) {
	System.out.println(e.getMessage());
} finally {
}
```


细节3.

可以进行 try-finally 配合使用, 这种用法相当于没有捕获异常，
因此程序会直接崩掉/退出。
应用场景: 就是执行一段代码，不管是否发生异常， 都必须执行某个业务逻辑. 比如说 代码挂了, 就必须通知另外一个个模块 
```java

 
try{
	int n1 = 10;
	int n2 = 0;
	System.out.println(n1 / n2);
}finally {
	System.out.println("执行了finally..");  // 执行完 这句后, 程序就崩了, jvm 抛出一个throw. 不会再 执行 System.out.println("程序继续执行.."); 了 
}
System.out.println("程序继续执行..");

}

```


## 3.2 try-catch练习

练习1.
```java
try {
            String[] names = new String[3];//String[]数组  这是首 names 中 每个 元素 都为 null
            if (names[1].equals("tom")) {//NullPointerException
                System.out.println(names[1]);
            } else {
                names[3] = "hspedu";
            }
            return 1;
        } catch (ArrayIndexOutOfBoundsException e) {
            return 2;
        } catch (NullPointerException e) {//捕获
            return 3;
        } finally { //必须执行
            return 4; //返回4
        }
    }
 
    public static void main(String[] args) {
        System.out.println(method()); //4
    }
//第三行出现异常直接跳到catch捕获错误
//执行return 3，但是finally是必须执行的，所以return 4
```


练习2
```java
int i = 1;
try {
	i++; //i = 2
	String[] names = new String[3];
	if (names[1].equals("tom")) {//空指针
		System.out.println(names[1]);
	} else {
		names[3] = "hspedu";
	}
	return 1;
} catch (ArrayIndexOutOfBoundsException e) {
	return 2;
} catch (NullPointerException e) {
	return ++i; //i = 3
} finally {//必须执行
	return ++i; //i = 4
}
}

public static void main(String[] args) {
System.out.println(method());
}
```


练习3.
```java
int i = 1;//i = 1
try {
	i++;// i=2
	String[] names = new String[3];
	if (names[1].equals("tom")) { //空指针
		System.out.println(names[1]);
	} else {
		names[3] = "hspedu";
	}
	return 1;
} catch (ArrayIndexOutOfBoundsException e) {
	return 2;
} catch (NullPointerException e) {
	return ++i;  // i = 3 => 保存临时变量 temp = 3;
} finally {
	++i; //i = 4
	System.out.println("i=" + i);// i = 4
}
}

public static void main(String[] args) {
System.out.println(method());// 3
}
```

最终 结果是 
输出 
i=4
3

i=4 在 3 的上一行

练习4.
如果用户输入的不是一个整数，就提示他反复输入，知道输入一个整数为止
```java
//思路
//1. 创建Scanner对象
//2. 使用无限循环，去接收一个输入
//3. 然后将该输入的值，转成一个int
//4. 如果在转换时，抛出异常，说明输入的内容不是一个可以转成int的内容
//5. 如果没有抛出异常，则break 该循环

statc void test (){
	Scanner scanner = new Scanner(System.in);
	int num = 0;
	String inputStr = "";
	while (true) {
	
		System.out.println("请输入一个整数:"); //
		inputStr = scanner.next();
		try {
			num = Integer.parseInt(inputStr); //这里是可能抛出异常, 
			break; // 如果上一步没有抛出异常, 就会执行 break 
		} catch (NumberFormatException e) {
			System.out.println("你输入的不是一个整数:");
		}
	}
	
	System.out.println("你输入的值是=" + num);
	}


然后在主程序中 执行 test()
```

以下是Utility中读取整形的源码，大家可以对比以下
```java
/**
 * 功能：读取键盘输入的整型，长度小于2位
 * @return 整数
 */
public static int readInt() {
	int n;
	for (; ; ) {
		String str = readKeyBoard(10, false);//一个整数，长度<=10位
		try {
			n = Integer.parseInt(str);//将字符串转换成整数
			break;
		} catch (NumberFormatException e) {
			System.out.print("数字输入错误，请重新输入：");
		}
	}
	return n;
}
```


# 4 throws异常处理机制

## 4.1 基本介绍
1. 如果一个方法（中的语句执行时）可能生成某种异常，但是并不能确定如何处理这种异常，则此方法应显示地声明抛出异常，<mark>表明该方法将不对这些异常进行处理</mark>，而由该方法的调用者负责处理. 方法的调任者 可以自己选择 是处理 整个 异常, 还是不处理这个异常. 
2. 同一个 throws 可以抛出多种异常 `accessModifier returnType methodName() throws ExceptionType1, ExceptionType2 … {}`
3. 在方法声明中用throws语句可以声明抛出异常的列表，throws后面的异常类型可以是方法中产生的异常类型，也可以是它的父类. 
	1. <mark>对于没有声明的抛出异常的种类, 则不做任何处理</mark>
		1. 就说 写成 throws Exception 和 throws FileNotFoundException  都能抛出 FileNotFoundException 这种类型的 Exception 
4. 对于编译异常, 程序中必须写有有相关代码 (try-catch, 或者 throws) 进行处理, 不然会在 IDE 显示出错误
	1. ![](image/Pasted%20image%2020230409140225.png)
5. 对于运行时的异常, 程序中如果没有处理, 默认就是 throws的方式处理
6. 子类重写父类的方法的时候, 对于抛出异常的规定:
	1. 子类重写的方法, 所抛出的异常类型 要么 和父类抛出的异常一致, 要么为父类拍出的异常的类型的子类型 . 必须有父子之间的关系 
7. <mark>在throws 过程中,如果有方法 try-catch, 就相当于处理异常, 就可以不必throws </mark>



![](image/Pasted%20image%2020230409140209.png)

![](image/Pasted%20image%2020230409010922.png)


![](image/Pasted%20image%2020230409134456.png)

## 4.2 案例 1

![](image/Pasted%20image%2020230409135155.png)



## 4.3 案例 2: 不显式写出 throws
//1.对于编译异常，程序中必须处理，比如 try-catch 或者 throws
//2.对于运行时异常，程序中如果没有处理，默认就是throws的方式处理
```java
public static void main(String[] args) {
        f2();
    }
 
public static void f2() /*throws ArithmeticException*/ {


	int n1 = 10;
	int n2 = 0;
	double res = n1 / n2;
}
```

上面的 代码 自动相当于 下面
```java
public static void main(String[] args) throws ArithmeticException {
        f2();
    }
 
public static void f2() throws ArithmeticException {


	int n1 = 10;
	int n2 = 0;
	double res = n1 / n2;
}
```


异常最终抛给了 jvm. JVM 处理 代码相当的简单暴力 , 就是如下 . 直接显示 message 
![](image/Pasted%20image%2020230409140457.png)

## 4.4 案例3 : 方法抛出编译异常, 调用者也需要显式抛出这个编译异常
小结：即若一个方法抛出编译异常，则谁调用这个方法，谁中也要写出代码 来要处理这个编译异常
```java
public static void f1() {
	//这里大家思考问题 飞()调用f3() 会报错
	//1. 因为f3() 方法抛出的是一个编译异常
	//2. 即这时，就要f1() 必须处理这个编译异常
	//3. 在f1() 中，要么 try-catch-finally ,或者继续throws 这个编译异常
	f3(); // 会抛出异常
}

public static void f3() throws FileNotFoundException {
	FileInputStream fis = new FileInputStream("d://aa.txt");
}
 
```

这样写下面这样就不会报错了
```java
public static void f1() throws FileNotFoundException {
	f3(); // 会抛出异常
}

public static void f3() throws FileNotFoundException {
	FileInputStream fis = new FileInputStream("d://aa.txt");
}
```

## 4.5 案例: 方法抛出运行异常, 调用者不需要显式抛出这个编译异常

因为有默认处理机制

```java
public static void f4() {
	//1. 在f4()中调用方法f5() 是OK 不会报错 
	//2. 原因是f5() 抛出的是运行异常
	//3. 而java中，并不要求程序员显示处理,因为有默认处理机制
	f5();
}

public static void f5() throws ArithmeticException {

}
```

## 4.6 案例:  子类重写父类的方法

子类重写父类的方法时，对抛出异常的规定:子类重写的方法，
所抛出的异常类型要么和父类抛出的异常一致，要么为父类抛出的异常类型的子类型
在throws 过程中，如果有方法 try-catch , 就相当于处理异常，就可以不必throws
这里我们就必须要搞清楚异常之间的继承和实现关系，因此我们需要熟练掌握异常体系图

```java
class Father { //父类
    public void method() throws RuntimeException {
    }
}
 
class Son extends Father {//子类

    @Override
    public void method() throws ArithmeticException {   // 这里如果写 Exception 就不行 , 会报错. 因为 Exception 的范围 比 RuntimeException 大.  如果写 FileNotFoundException 也不行. 因为 FileNotFoundException 和 RuntimeException 没有 父子关系 
    }
}
```


# 5 自定义异常及其抛出 throw 和 throw new
1.基本概念
当程序中出现某些“错误”，但该错误信息并没有在Throwable子类中描述处理，这个时候可以自己设计异常类，用于描述该错误信息
throw关键字用于显式地抛出一个异常。 当引发异常时，程序执行的流程从try块转移到catch块。我们在方法中使用throw关键字。

其语法为：
throw throwableObject;
Throwable对象是Throwable类或Throwable类的子类的实例。

2.自定义异常的步骤
1）定义类：自定义异常类名继承Exception 或 RuntimeException
2）如果继承Exception ， 属于编译异常
3）如果继承RuntimeException，属于运行异常

## 5.1 案例引入

实例1 
当我们接受Person 对象年龄的时候, 要求范围在 18-120 之间, 否则抛出一个自定义异常 ( 要求继承 RuntimeException), 斌给出提示信息 

这里出现的throw和前面的throws是有区别的
throws 是异常处理的一种方式，通常在方法声明处出现，后面加异常类型
throw 是手动生成异常对象的关键字，通常在方法体中出现，后面加异常对象

```java
package com.hspedu.customexception_;
/**
 * @author 韩顺平
 * @version 1.0
 */

public class CustomException {
    public static void main(String[] args) /*throws AgeException*/ {
        int age = 180;
        //要求范围在18 – 120 之间，否则抛出一个自定义异常
        if (!(age >= 18 && age <= 120)) {
            //这里我们可以通过构造器，设置信息
            throw new AgeException("年龄需要在18~120 之间");
        }
        System.out.println("你的年龄范围正确.");
    }
}


//自定义一个异常
//老韩解读
//1. 一般情况下，我们自定义异常是继承RuntimeException
//2. 即把自定义异常做成运行时异常，好处时，我们可以使用默认的处理机制
//3. 即比较方便

class AgeException extends RuntimeException {
    public AgeException(String message) { //构造器
        super(message);
    }
}
```


示例2：

```java

Java throw关键字class Main {

public static void divideByZero() {

throw new ArithmeticException("试图除以0");

}

public static void main(String[] args) {

divideByZero();

}

}
```


输出结果Exception in thread "main" java.lang.ArithmeticException: 试图除以0
at Main.divideByZero(Main.java:3)
at Main.main(Main.java:7)
exit status 1

在此示例中，我们明确抛出 ArithmeticException.
注意： ArithmeticException是未经检查的异常。通常没有必要处理未经检查的异常。


## 5.2 为什么 喜欢继承 运行异常, 不喜欢用 继承编译异常 : 
因为 用 继承编译异常, 还需要在 调用者 那里 写上 throws xxxx
如下 
```java
package com.hspedu.customexception_;
/**
 * @author 韩顺平
 * @version 1.0
 */

public class CustomException {
    public static void main(String[] args) throws AgeException {  // 这里必须写上 throws AgeException, 不然编译的时候 会报错 
        int age = 180;
        //要求范围在18 – 120 之间，否则抛出一个自定义异常
        if (!(age >= 18 && age <= 120)) {
            //这里我们可以通过构造器，设置信息
            throw new AgeException("年龄需要在18~120 之间");
        }
        System.out.println("你的年龄范围正确.");
    }
}

class AgeException extends Exception {  // 为自定义一个编译异常, 不是运行异常
    public AgeException(String message) { //构造器
        super(message);
    }
}
```

# 6 throw 和throws 的区别

![](image/Pasted%20image%2020230409142502.png)



## 6.1 例子

![](image/Pasted%20image%2020230409142908.png)

![](image/Pasted%20image%2020230409142515.png)

![](image/Pasted%20image%2020230409142804.png)

# 7 作业

## 7.1 

![](image/Pasted%20image%2020230409143130.png)


```java
public class Homework01 {
    public static void main(String[] args) {
        /*
        编写应用程序EcmDef.java，接收命令行的两个参数(整数)，计算两数相除。
计算两个数相除，要求使用方法 cal(int n1, int n2)
对数据格式不正确(NumberFormatException)、缺少命令行参数(ArrayIndexOutOfBoundsException)、除0 进行异常处理(ArithmeticException)。
         */
 
        try {
 
            //先验证输入的参数的个数是否正确 两个参数
            if(args.length != 2) {
                throw new ArrayIndexOutOfBoundsException("参数个数不对");
            }
 
            //先把接收到的参数，转成整数
            int n1 = Integer.parseInt(args[0]);
            int n2 = Integer.parseInt(args[1]);
 
            double res = cal(n1, n2);//该方法可能抛出ArithmeticException, 为运行异常
            System.out.println("计算结果是=" + res);
 
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println(e.getMessage());
        } catch (NumberFormatException e) {
            System.out.println("参数格式不正确，需要输出整数");
        } catch (ArithmeticException e) {
            System.out.println("出现了除0的异常");
        }
 
 
    }
    //编写cal方法，就是两个数的商
    public static double cal(int n1, int n2) {
        return n1 / n2;
    }
}
```


配置输入的参数

![](image/Pasted%20image%2020230409143533.png)


## 7.2 

![](image/Pasted%20image%2020230409143621.png)

会发生三种异常，空指针，越界，类型转换。
类型转换 的异常:  因为 0 的运行类型 本身为 String , 不是 Integer. 所以要把 String 向下转型为 Integer, 肯定会发生 异常 


## 7.3 

![](image/Pasted%20image%2020230409143723.png)

因为 异常已经被捕获, 所以 System.out.println("D") 会被执行 

## 7.4 

![](image/Pasted%20image%2020230409144425.png)

![](image/Pasted%20image%2020230409144504.png)